#:schema node_modules/wrangler/config-schema.json
name = "cobra-sol-dier"
compatibility_date = "2024-11-12"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "cobrainsurecontent"


[[d1_databases]]
binding = "DB"
database_name = "leads-cobra-solutions"
database_id = "e9dabbc6-da93-4c90-91b7-dbe395158ed3"

[[kv_namespaces]]
binding = "KV"
id = "6a8b43e3f683433792616cd2fd026f80"
